volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    container_name: foodgram-db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    container_name: foodgram-backend
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    container_name: foodgram-frontend
    build: ./frontend
    command: cp -r /app/result_build/build/. /frontend_static/
    volumes:
      - ./frontend:/app/result_build
      - static:/frontend_static
    depends_on:
      - backend
  nginx:
    image: nginx:1.21.3-alpine
    container_name: foodgram-nginx
    ports:
      - "8000:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - media:/media
    depends_on:
      - backend
